config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: []
  devise_for :admins, path: 'dashboard', only: %i[sessions unlock]


  namespace :dashboard do
    get '/', to: 'index#index'
    resources :merchants do
      member do
        get 'transactions', action: :transactions
        get 'download_qrcode', action: :download_qrcode
      end
    end
  end

  root 'dashboard/index#index'

  namespace :api, path: 'api/(v:api)', defaults: { format: 'json' } do
    devise_scope :user do
      post '/users' => '/users/registrations#create'
      delete '/users/sign_out' => '/users/sessions#destroy'
      post '/users/sign_in' => '/users/sessions#create'
    end
    resources :cards, only: [:index, :create, :destroy] do
      member do
        post '/set_as_default', action: :set_as_default
      end
    end
    resources :transactions, only: [:index, :create]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates :name, :email, :vat_number, :contact_number, :address, presence: true
  validates_format_of :email, with: /\A[^@\s]+@[^@\s]+\z/, allow_blank: true

  has_many :transactions, -> { order(created_at: :desc)}, dependent: :destroy

  after_save :add_qrcode

  private

  def add_qrcode
    qrcode = RQRCode::QRCode.new(self.as_json(only: %i[id name email contact_number address]).to_json)
    self.update_column(:qrcode, qrcode.as_html)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :merchant

  validates :charge_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :transactions, -> { order(created_at: :desc)}, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  include Error::ErrorHandler

  protect_from_forgery prepend: true

  acts_as_token_authentication_handler_for User

  respond_to :json
end

app/controllers/api/cards_controller.rb
class Api::CardsController < Api::BaseController

  def index
    return render(json: { cards: [] }) unless current_user.customer_id
    customer = get_customer
    render json: { cards: customer.sources.all(object: 'card')['data'].map { |card| card.as_json.merge(active_card: card.id.eql?(customer.default_source)) } }
  end

  def create
    customer = stripe_customer
    customer.sources.create(source: params[:card_token])
    render json: { message: 'Success' }
  end

  def destroy
    customer = get_customer
    customer.sources.retrieve(params[:id]).delete
    render json: { message: 'Success' }
  end

  def set_as_default
    customer = get_customer
    customer.default_source = params[:id]
    customer.save
    render json: { message: 'Success' }
  end

  private

  def stripe_customer
    current_user.customer_id ? get_customer : create_customer
  end

  def get_customer
    Stripe::Customer.retrieve(current_user.customer_id)
  end

  def create_customer
    customer = Stripe::Customer.create(email: current_user.email, description: "Customer app_id #{current_user.id}")
    current_user.update(customer_id: customer.id)
    customer
  end
end

app/controllers/api/transactions_controller.rb
class Api::TransactionsController < Api::BaseController
  def index
    transactions = current_user.transactions.eager_load(:merchant)
    render json: { transactions: transactions.map { |transaction| transaction.as_json.merge(merchant: transaction.merchant.as_json(only: %i[name email contact_number address amount])) } }
  end

  def create
    merchant = Merchant.find_by_id(params[:merchant_id])
    return render json: { error: 'Merchant not found' }, status: :not_found unless merchant

    amount = params[:amount].to_f
    return render json: { error: 'Amount must be greater than 0' }, status: :unprocessable_entity if amount.zero?

    transaction = Stripe::Charge.create(
      amount: (amount  * 100).to_i,
      currency: 'usd',
      customer: current_user.customer_id,
      :description => "Charge for #{merchant.name} (#{merchant.id}) #{merchant.email}"
    )
    current_user.transactions.create(merchant_id: merchant.id, charge_id: transaction.id, amount: transaction.amount.to_f / 100)
    render json: { message: 'Success' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ::ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_admin!

  layout 'dashboard'
end

app/controllers/dashboard/index_controller.rb
class Dashboard::IndexController  < Dashboard::ApplicationController
  def index
    redirect_to dashboard_merchants_path
  end
end

app/controllers/dashboard/merchants_controller.rb
class Dashboard::MerchantsController < Dashboard::ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy, :transactions, :download_qrcode]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    redirect_to edit_dashboard_merchant_path(@merchant)
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
    @merchant = Merchant.find(params[:id])
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    if @merchant.save
      redirect_to edit_dashboard_merchant_path(@merchant), notice: 'Merchant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to dashboard_merchant_url(@merchant), notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    redirect_to dashboard_merchants_url, notice: 'Merchant was successfully destroyed.'
  end

  def transactions
    @transactions = @merchant.transactions.joins(:user)
  end

  def download_qrcode
    qrcode = RQRCode::QRCode.new(@merchant.as_json(only: %i[id name email contact_number address]).to_json).as_png(size: 400)
    send_data qrcode, type: 'image/png'
  end

  private

  def set_merchant
    @merchant = Merchant.find(params[:id])
  end

  def merchant_params
    params.require(:merchant).permit(:name, :email, :vat_number, :contact_number, :address)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json

  protected

  def sign_up_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  skip_before_filter :verify_signed_out_user
  acts_as_token_authentication_handler_for User
  skip_before_action :authenticate_user_from_token!, only: :create

  # DELETE /resource/sign_out
  def destroy
    user = User.find_by_authentication_token_and_email(params[:user_token], params[:user_email])

    if user
      user.authentication_token = nil
      user.save!
    else
      return render json: { errors: 'Invalid Token'}, status: :unauthorized
    end
    super
  end

  private

  def resource_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/dashboard/index/index.html.haml
.page-header.border-t
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-home.page-header-icon
        Dashboard
    .col-xs-6.col-sm-6.text-right
      %h1
.row

app/views/dashboard/merchants/_form.html.haml
= simple_form_for [:dashboard, merchant], html: { id: 'form-merchant' } do |f|
  .x_panel
    .x_title
      %h2 Merchant Details
      %ul.nav.navbar-right.panel_toolbox
        %li.right
          %a.collapse-link
            %i.fa.fa-chevron-up
      .clearfix
    .x_content
      .row
        .col-xs-12
          = f.input :name, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :email, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :vat_number, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :contact_number, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :address, input_html: { class: 'form-control' }

app/views/dashboard/merchants/edit.html.haml
.page-header
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-briefcase.page-header-icon
        #{@merchant.name}
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to dashboard_merchants_path do
          #button-cancel-merchant.btn.btn-lg.btn-cancel
            Cancel
        %button.submit-form-button.btn.btn-primary.btn-lg{ 'data-target': 'merchant' } Save
.row
  .col-xs-12.col-md-7
    = render 'form', merchant: @merchant
    .x_panel
      .x_title
        %h2 Merchant QRCode
        %ul.nav.navbar-right.panel_toolbox
          %li.right
            %a.collapse-link
              %i.fa.fa-chevron-up
        .clearfix
      .x_content
        .row
          .col-sm-12.text-center#div-to-print
            = raw @merchant.qrcode
        .row
          .col-sm-12.text-right
            = link_to 'Download', download_qrcode_dashboard_merchant_path(@merchant), class: 'btn btn-primary btn-medium', download: "merchant_#{@merchant.id}_qrcode.png"
            = link_to 'Print QRCOde', '#', class: 'print-qrcode btn btn-primary btn-medium'
  .col-xs-12.col-md-5
    .x_panel
      .x_title
        %h2 Merchant Transactions
        %ul.nav.navbar-right.panel_toolbox
          %li.right
            %a.collapse-link
              %i.fa.fa-chevron-up
        .clearfix
      .x_content
        .row
          .col-xs-9
            Total transactions: #{@merchant.transactions.count}
          .col-xs-3.text-right
            = link_to 'View', transactions_dashboard_merchant_path(@merchant)

app/views/dashboard/merchants/index.html.haml
.page-header.border-t
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-briefcase.page-header-icon
        Merchants
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to new_dashboard_merchant_path, class: 'btn btn-primary  btn-lg' do
          Add Merchant
.row
  .col-sm-12
    .table-responsive
      %table.table.table-striped.jambo_table.bulk_action
        %thead
          %tr.headings
            %th{colspan: '14'}
              .row
                .col-sm-offset-4.col-xs-4.col-sm-3.text-right
                .col-xs-8.col-sm-5
                  -#= render 'admin/dashboards/search_form', target: 'merchants', query: params[:query], attr: 'name'
          %tr.headings
            %th.column-title
              Name
            %th.column-title
              Email
            %th.column-title
              Vat Number
            %th.column-title
              Address
            %th.column-title.no-link.last
              %span.nobr Action
        - if @merchants.present?
          %tbody
            - @merchants.each do |merchant|
              %tr
                %td.a-center
                  = link_to edit_dashboard_merchant_path(merchant) do
                    = merchant.name
                %td= merchant.email
                %td= merchant.vat_number
                %td.a-right.a-right= merchant.address
                %td.last{width: '100'}
                  .btn-group
                    = link_to edit_dashboard_merchant_path(merchant), class: 'btn btn-xs btn-default' do
                      %i.fa.fa.fa-pencil
                    = link_to dashboard_merchant_path(merchant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' do
                      %i.fa.fa-trash
        - else
          %tbody
            %tr.even.pointer
              %td{colspan: '14'}
                No merchants to display

-#= paginate @merchants

app/views/dashboard/merchants/new.html.haml
.page-header
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-briefcase.page-header-icon
        New Merchant
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to dashboard_merchants_path do
          #button-cancel-merchant.btn.btn-lg.btn-cancel
            Cancel
        %button.submit-form-button.btn.btn-primary.btn-lg{ 'data-target': 'merchant' } Save
.row
  .col-xs-12.col-md-7
    = render 'form', merchant: @merchant

app/views/dashboard/merchants/transactions.html.haml
.page-header.border-t
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-briefcase.page-header-icon
        Merchants
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to dashboard_merchant_path(@merchant), class: 'btn btn-primary  btn-lg' do
          Back
.row
  .col-sm-12
    .table-responsive
      %table.table.table-striped.jambo_table.bulk_action
        %thead
          %tr.headings
            %th{colspan: '14'}
              .row
                .col-sm-offset-4.col-xs-4.col-sm-3.text-right
                .col-xs-8.col-sm-5
          -#= render 'admin/dashboards/search_form', target: 'transactions', query: params[:query], attr: 'name'
          %tr.headings
            %th.column-title
              User
            %th.column-title
              Amount
            %th.column-title
              Date
        - if @transactions.present?
          %tbody
            - @transactions.each do |merchant|
              %tr
                %td.a-center= merchant.user.email
                %td= merchant.amount
                %td= merchant.created_at.strftime('%Y %B %d %H:%M')
        - else
          %tbody
            %tr.even.pointer
              %td{colspan: '14'}
                No transactions to display

                -#= paginate @transactions

app/views/index/index.html.erb
<%= current_user.id if current_user %>

app/views/layouts/admin/_sidenav.html.haml
.col-md-3.left_col
  .left_col.scroll-view
    .navbar.nav_title
      = link_to dashboard_path, class: 'site_title' do
        %span Vyya
    .clearfix
    %br
    #sidebar-menu.main_menu_side.hidden-print.main_menu
      .menu_section
        %ul.nav.side-menu
          -#%li
          -#  %a
          -#    %i.fa.fa-home
          -#    Dashboard
          -#    %span.fa.fa-chevron-down
          -#  %ul.nav.child_menu{style: 'display: none'}
          -#    %li
          -#      = link_to 'Dashboard', dashboard_path
          %li
            %a
              %i.fa.fa-briefcase
              Merchants
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'List Merchants', dashboard_merchants_path
              %li
                = link_to 'Add Merchant', new_dashboard_merchant_path
    .sidebar-footer.hidden-small
      = link_to destroy_admin_session_path, method: :delete do
        %span.glyphicon.glyphicon-off{ 'aria-hidden': 'true' }

app/views/layouts/admin/_topnav.html.haml
.top_nav
  .nav_menu
    %nav{ role: 'navigation' }
      .nav.toggle
        %a#menu_toggle
          %i.fa.fa-bars
      %ul.nav.navbar-nav.navbar-right
        %li
          %a.user-profile.dropdown-toggle{'aria-expanded': 'false', 'data-toggle': 'dropdown', href: 'javascript:;'}
            Admin
            %span.fa.fa-angle-down
          %ul.dropdown-menu.dropdown-usermenu.pull-right
            %li
              = link_to destroy_admin_session_path, method: :delete do
                %i.fa.fa-sign-out.pull-right
                Log Out

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vyya</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Vyya
    = csrf_meta_tags
    = stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'dashboard', media: 'print'
    = javascript_include_tag 'dashboard', 'data-turbolinks-track': 'reload'
%body.nav-md
  .container.body
    .main_container
      = render 'layouts/admin/sidenav'
      = render 'layouts/admin/topnav'
      .right_col{ role: 'main' }
        = yield

  = javascript_include_tag 'gentelella-custom', 'data-turbolinks-track': 'reload'